
package ch.docbox.ws.cdachservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CDACHServices", targetNamespace = "http://ws.docbox.ch/CDACHServices/", wsdlLocation = "file:wsdl/CDACHServices.wsdl")
public class CDACHServices_Service
    extends Service
{

    public final static URL CDACHSERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ch.docbox.ws.cdachservices.CDACHServices_Service.class.getName());

    static {
    	URL baseUrl = ch.docbox.ws.cdachservices.CDACHServices_Service.class.getResource("");
    	URL url = null;
        try {
    		url = new URL(baseUrl+"/CDACHServices.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:wsdl/CDACHServicesTest.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CDACHSERVICES_WSDL_LOCATION = url;
    }

    public CDACHServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CDACHServices_Service() {
        super(CDACHSERVICES_WSDL_LOCATION, new QName("http://ws.docbox.ch/CDACHServices/", "CDACHServices"));
    }

    /**
     * 
     * @return
     *     returns CDACHServices
     */
    @WebEndpoint(name = "CDACHServices")
    public CDACHServices getCDACHServices() {
        return super.getPort(new QName("http://ws.docbox.ch/CDACHServices/", "CDACHServices"), CDACHServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CDACHServices
     */
    @WebEndpoint(name = "CDACHServices")
    public CDACHServices getCDACHServices(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.docbox.ch/CDACHServices/", "CDACHServices"), CDACHServices.class, features);
    }

}
